name: Test

on:
  push:
    branches:
      - main
      - tdb/test-runner
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python runtests.py
